<?xml version="1.0" encoding="UTF-8"?><testrun name="LocacaoServiceTest.naoDeveAlugarFilmeParaNegativadoSPC" project="TestesUnitarios" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testcase name="naoDeveAlugarFilmeParaNegativadoSPC" classname="br.ce.wcaquino.servicos.LocacaoServiceTest" time="0.406">
    <failure>java.lang.AssertionError: Expected test to throw (an instance of br.ce.wcaquino.exceptions.LocadoraException and exception with message a string containing "Usu√°rio Negativado")&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.rules.ExpectedException.failDueToMissingException(ExpectedException.java:263)&#13;
	at org.junit.rules.ExpectedException.access$200(ExpectedException.java:106)&#13;
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:245)&#13;
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</failure>
  </testcase>
</testrun>
